version: '3.7'

networks:
  common:
    external:
      name: common

services:
  consul:
    restart: always
    image: consul:latest
    container_name: consul
    networks: { common: { ipv4_address: 172.20.0.2 } }
    hostname: consul
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "enable_script_checks": true}'
      - "CONSUL_ALLOW_PRIVILEGED_PORTS="
    command: [ "consul", "agent", "-dev", "-dns-port=53","-recursor=8.8.8.8", "-client=0.0.0.0" ]

